// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentTodo.Api.Models;

#nullable disable

namespace StudentTodo.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20230529215514_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentTodo.Api.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("student_description");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("student_gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_name");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("student_title");

                    b.HasKey("StudentId");

                    b.ToTable("tb_student", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
